export const FormAction = {
  SET_GENRE: 'SET_GENRE',
  SET_MOOD: 'SET_MOOD',
  SET_LEVEL: 'SET_LEVEL',
  UPDATE_AVAILABLE_MOODS: 'UPDATE_AVAILABLE_MOODS',
};

export const ApiAction = {
  FETCH_START: 'FETCH_START',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',
};